name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.vb'
    - '**.vbproj'
    - '**.sln'

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    # 1. Setup MSBuild (The builder for .NET Framework)
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    # 2. Setup NuGet (To restore packages for older framework)
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    # 3. Restore dependencies using NuGet.exe
    - name: Restore Packages
      run: nuget restore

    # 4. Build using MSBuild
    - name: Build
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU"